***to use this file, rename it secrets.toml and delete this line, then change the values below***

# Values here will be passed directly to the connect method of the Python connector.
# So if you want to use MFA, or the externalbrowser authentication method (which is **really easy**)
# just set them up below.
[snowflake]
user="your username"
password="your password"
account="your snowflake account" #eg. au_demo32
region="your snowflake region" #eg. ap-southeast-2, or australia-east.azure
role="your snowflake role"  # will need to be AccountAdmin or with adequate permissions over the Snowflake Account Usage schema
database="snowflake" #no need to change this
schema="account_usage" # no need to change this
warehouse="your virtual warehouse name" # a virtual warehouse the role above has USAGE on.